import DbState from './state.js';
import { Network } from './schema.js';

const rpcs = [
  {
    network: 'arbitrum',
    url: 'https://arbitrum.blockpi.network/v1/rpc/public',
    chainId: 42161,
    symbol: 'ETH',
    block_explorer: 'https://arbiscan.io/',
    type: 'Mainnet',
  },
  {
    network: 'arbitrum',
    url: 'https://rpc.ankr.com/arbitrum',
    chainId: 42161,
    symbol: 'ETH',
    block_explorer: 'https://arbiscan.io/',
    type: 'Mainnet',
  },
  {
    network: 'avalanche',
    url: 'https://api.avax.network/ext/bc/C/rpc',
    chainId: 43114,
    symbol: 'AVAX',
    block_explorer: 'https://snowtrace.io',
    type: 'Mainnet',
  },
  {
    network: 'avalanche',
    url: 'https://rpc.ankr.com/avalanche',
    chainId: 43114,
    symbol: 'AVAX',
    block_explorer: 'https://snowtrace.io',
    type: 'Mainnet',
  },
  {
    network: 'avalanche',
    url: 'https://avalanche.api.onfinality.io/public/ext/bc/P',
    chainId: 43114,
    symbol: 'AVAX',
    block_explorer: 'https://snowtrace.io',
    type: 'Mainnet',
  },
  {
    network: 'avalanche-fuji',
    url: 'https://api.avax-test.network/ext/bc/C/rpc',
    chainId: 43113,
    symbol: 'AVAX',
    block_explorer: 'https://testnet.explorer.avax.network/',
    type: 'Testnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc.meowrpc.com',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://1rpc.io/bnb',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://binance.nodereal.io',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed.binance.org',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed1.binance.org',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed1.defibit.io',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed1.ninicoin.io',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed2.binance.org',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed2.defibit.io',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed2.ninicoin.io',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed3.binance.org',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed3.defibit.io',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed3.ninicoin.io',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed4.binance.org',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed4.defibit.io',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-dataseed4.ninicoin.io',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-mainnet.gateway.pokt.network/v1/lb/6136201a7bad1500343e248d',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc-mainnet.public.blastapi.io',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc.blockpi.network/v1/rpc/public',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc.publicnode.com',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bsc.rpc.blxrbdn.com',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bscrpc.com',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain-testnet',
    url: 'https://data-seed-prebsc-1-s1.binance.org:8545',
    chainId: 97,
    symbol: 'BNB',
    block_explorer: 'https://testnet.bscscan.com',
    type: 'Testnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://koge-rpc-bsc.48.club',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://rpc-bsc.48.club',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://rpc.ankr.com/bsc',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://rpc.ankr.com/bsc',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'bnb-chain',
    url: 'https://bnb.api.onfinality.io/public',
    chainId: 56,
    symbol: 'BNB',
    block_explorer: 'https://bscscan.com',
    type: 'Mainnet',
  },
  {
    network: 'celo',
    url: 'https://rpc.ankr.com/celo',
    chainId: 42220,
    symbol: 'CELO',
    block_explorer: 'https://celoscan.com',
    type: 'Mainnet',
  },
  {
    network: 'celo',
    url: 'https://forno.celo.org',
    chainId: 42220,
    symbol: 'CELO',
    block_explorer: 'https://celoscan.com',
    type: 'Mainnet',
  },
  {
    network: 'celo',
    url: 'https://rpc.ankr.com/celo',
    chainId: 42220,
    symbol: 'CELO',
    block_explorer: 'https://celoscan.com',
    type: 'Mainnet',
  },
  {
    network: 'celo',
    url: 'https://1rpc.io/celo',
    chainId: 42220,
    symbol: 'CELO',
    block_explorer: 'https://celoscan.com',
    type: 'Mainnet',
  },
  {
    network: 'condor-testnet',
    url: 'https://testnet.condor.systems/rpc',
    chainId: 188881,
    symbol: 'CONDOR',
    block_explorer: 'https://explorer.condor.systems',
    type: 'Testnet',
  },
  {
    network: 'cronos',
    url: 'https://evm-cronos.crypto.org',
    chainId: 25,
    symbol: 'CRO',
    block_explorer: 'https://cronos.crypto.org/explorer/',
    type: 'Mainnet',
  },
  {
    network: 'elastos',
    url: 'https://api.elastos.io/eth',
    chainId: 20,
    symbol: 'ELA',
    block_explorer: 'https://explorer.elaeth.io/',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'http://eth.drpc.org',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://eth.meowrpc.com',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://1rpc.io/eth',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://api.bitstack.com/v1/wNFxbiJyQsSeLrX8RRCHi7NpRxrlErZk/DjShIqLishPCTB9HiMkPHXjUM9CNM9Na/ETH/mainnet',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://api.securerpc.com/v1',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://api.zmok.io/mainnet/oaen6dy8ff6hju9k',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://beta-be.gashawk.io:3001/proxy/rpc',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://cloudflare-eth.com',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://eth-mainnet.nodereal.io/v1/1659dfb40aa24bbb8153a677b98064d7',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://eth-mainnet.public.blastapi.io',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://eth-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://eth-rpc.gateway.pokt.network',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://eth.api.onfinality.io/public',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://eth.drpc.org',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://eth.llamarpc.com',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://eth.rpc.blxrbdn.com',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://ethereum.blockpi.network/v1/rpc/public',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://ethereum.publicnode.com',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://rpc.ankr.com/eth',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://rpc.builder0x69.io',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://rpc.flashbots.net',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://rpc.payload.de',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://singapore.rpc.blxrbdn.com',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://uk.rpc.blxrbdn.com',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'ethereum',
    url: 'https://virginia.rpc.blxrbdn.com',
    chainId: '0x1',
    symbol: 'ETH',
    block_explorer: 'https://etherscan.io',
    type: 'Mainnet',
  },
  {
    network: 'fantom',
    url: 'https://rpc.ftm.tools/',
    chainId: '0xfa',
    symbol: 'FTM',
    block_explorer: 'https://ftmscan.com',
    type: 'Mainnet',
  },
  {
    network: 'fantom-testnet',
    url: 'https://rpc.testnet.fantom.network/',
    chainId: '0xfa2',
    symbol: 'FTM',
    block_explorer: 'https://testnet.ftmscan.com',
    type: 'Testnet',
  },
  {
    network: 'fantom',
    url: 'https://fantom.api.onfinality.io/public',
    chainId: '0xfa',
    symbol: 'FTM',
    block_explorer: 'https://ftmscan.com',
    type: 'Mainnet',
  },
  {
    network: 'fuse',
    url: 'https://rpc.fuse.io',
    chainId: '0x7a',
    symbol: 'FUSE',
    block_explorer: 'https://explorer.fuse.io/',
    type: 'Mainnet',
  },
  {
    network: 'gnosis',
    url: 'https://rpc.gnosischain.com',
    chainId: '0x64',
    symbol: 'XDAI',
    block_explorer: 'https://blockscout.com/xdai/mainnet/',
    type: 'Mainnet',
  },
  {
    network: 'gnosis',
    url: 'https://gnosis.api.onfinality.io/public',
    chainId: '0x64',
    symbol: 'XDAI',
    block_explorer: 'https://blockscout.com/xdai/mainnet/',
    type: 'Mainnet',
  },
  {
    network: 'goerli',
    url: 'https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161',
    chainId: '0x5',
    symbol: 'ETH',
    block_explorer: 'https://goerli.etherscan.io',
    type: 'Testnet',
  },
  {
    network: 'harmony',
    url: 'https://api.harmony.one',
    chainId: '0x63564c40',
    symbol: 'ONE',
    block_explorer: 'https://explorer.harmony.one',
    type: 'Mainnet',
  },
  {
    network: 'harmony',
    url: 'https://api.s0.b.hmny.io',
    chainId: '0x6357d2e0',
    symbol: 'ONE',
    block_explorer: 'https://explorer.harmony.one',
    type: 'Testnet',
  },
  {
    network: 'harmony',
    url: 'https://harmony-mainnet.chainstacklabs.com',
    chainId: '0x63564c40',
    symbol: 'ONE',
    block_explorer: 'https://explorer.harmony.one',
    type: 'Mainnet',
  },
  {
    network: 'heco',
    url: 'https://http-mainnet-node.huobichain.com/',
    chainId: 128,
    symbol: 'HT',
    block_explorer: 'https://hecoinfo.com/',
    type: 'Mainnet',
  },
  {
    network: 'heco-testnet',
    url: 'https://http-testnet.hecochain.com',
    chainId: 256,
    symbol: 'HT',
    block_explorer: 'https://testnet.hecoinfo.com/',
    type: 'Testnet',
  },
  {
    network: 'hsc',
    url: 'https://http-mainnet.hoosmartchain.com',
    chainId: 70,
    symbol: 'HOO',
    block_explorer: 'https://hooscan.com',
    type: 'Mainnet',
  },
  {
    network: 'iotex',
    url: 'https://babel-api.mainnet.iotex.io',
    chainId: 4689,
    symbol: 'IOTEX',
    block_explorer: 'https://iotexscan.io/',
    type: 'Mainnet',
  },
  {
    network: 'kcc',
    url: 'https://rpc-mainnet.kcc.network',
    chainId: 321,
    symbol: 'KCS',
    block_explorer: 'https://scan.kcc.network',
    type: 'Mainnet',
  },
  {
    network: 'kcc-testnet',
    url: 'https://rpc-testnet.kcc.network',
    chainId: 322,
    symbol: 'tKCS',
    block_explorer: 'https://scan-testnet.kcc.network',
    type: 'Testnet',
  },
  {
    network: 'moonriver',
    url: 'https://rpc.moonriver.moonbeam.network',
    chainId: 1285,
    symbol: 'MOVR',
    block_explorer: 'https://blockscout.moonriver.moonbeam.network/',
    type: 'Mainnet',
  },
  {
    network: 'moonriver',
    url: 'https://moonriver.api.onfinality.io/public',
    chainId: 1285,
    symbol: 'MOVR',
    block_explorer: 'https://blockscout.moonriver.moonbeam.network/',
    type: 'Mainnet',
  },
  {
    network: 'nahmii',
    url: 'https://l2.nahmii.io',
    chainId: 5551,
    symbol: 'ETH',
    block_explorer: 'https://explorer.nahmii.io/',
    type: 'Mainnet',
  },
  {
    network: 'nahmii-testnet',
    url: 'https://l2.testnet.nahmii.io',
    chainId: 5553,
    symbol: 'ETH',
    block_explorer: 'https://explorer.testnet.nahmii.io/',
    type: 'Testnet',
  },
  {
    network: 'near',
    url: 'https://rpc.ankr.com/near',
    chainId: null,
    symbol: 'NEAR',
    block_explorer: '',
    type: 'Mainnet',
  },
  {
    network: 'okex',
    url: 'https://exchainrpc.okex.org',
    chainId: 66,
    symbol: 'OKT',
    block_explorer: 'https://www.oklink.com/okexchain',
    type: 'Mainnet',
  },
  {
    network: 'pando',
    url: 'https://eth-rpc-api.pandoproject.org/rpc',
    chainId: 398,
    symbol: 'PTX',
    block_explorer: 'https://explorer.pandoproject.org',
    type: 'Mainnet',
  },
  {
    network: 'polygon',
    url: 'http://polygon.drpc.org',
    chainId: '0x89',
    symbol: 'MATIC',
    block_explorer: 'https://explorer.matic.network/',
    type: 'Mainnet',
  },
  {
    network: 'polygon',
    url: 'https://matic-mainnet.chainstacklabs.com',
    chainId: '0x89',
    symbol: 'MATIC',
    block_explorer: 'https://explorer.matic.network/',
    type: 'Mainnet',
  },
  {
    network: 'polygon',
    url: 'https://polygon-rpc.com',
    chainId: '0x89',
    symbol: 'MATIC',
    block_explorer: 'https://explorer.matic.network/',
    type: 'Mainnet',
  },
  {
    network: 'mumbai',
    url: 'https://rpc-mumbai.maticvigil.com',
    chainId: '0x13881',
    symbol: 'MATIC',
    block_explorer: 'https://mumbai.polygonscan.com/',
    type: 'Testnet',
  },
  {
    network: 'polygon',
    url: 'https://polygon.api.onfinality.io/public',
    chainId: '0x89',
    symbol: 'MATIC',
    block_explorer: 'https://explorer.matic.network/',
    type: 'Mainnet',
  },
  {
    network: 'smartbch',
    url: 'https://smartbch.fountainhead.cash/mainnet',
    chainId: 10000,
    symbol: 'BCH',
    block_explorer: 'https://www.smartscan.cash/',
    type: 'Mainnet',
  },
  {
    network: 'solana',
    url: 'https://rpc.ankr.com/solana',
    chainId: null,
    symbol: 'SOL',
    block_explorer: 'https://solscan.io/',
    type: 'Mainnet',
  },
  {
    network: 'telos',
    url: 'https://mainnet.telos.net/evm',
    chainId: 40,
    symbol: 'TLOS',
    block_explorer: 'https://telos.net/',
    type: 'Mainnet',
  },
  {
    network: 'ubiq',
    url: 'https://rpc.octano.dev',
    chainId: 8,
    symbol: 'UBQ',
    block_explorer: 'https://ubiqscan.io/',
    type: 'Mainnet',
  },
  {
    network: 'sepolia',
    url: 'https://rpc2.sepolia.org',
    chainId: 11155111,
    symbol: 'ETH',
    block_explorer: 'https://sepolia.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'sepolia',
    url: 'https://eth-sepolia.g.alchemy.com/v2/demo',
    chainId: 11155111,
    symbol: 'ETH',
    block_explorer: 'https://sepolia.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'sepolia',
    url: 'https://ethereum-sepolia.blockpi.network/v1/rpc/public',
    chainId: 11155111,
    symbol: 'ETH',
    block_explorer: 'https://sepolia.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'sepolia',
    url: 'https://rpc.sepolia.org',
    chainId: 11155111,
    symbol: 'ETH',
    block_explorer: 'https://sepolia.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'sepolia',
    url: 'https://endpoints.omniatech.io/v1/eth/sepolia/public',
    chainId: 11155111,
    symbol: 'ETH',
    block_explorer: 'https://sepolia.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'goerli',
    url: 'https://eth-goerli.public.blastapi.io',
    chainId: 5,
    symbol: 'ETH',
    block_explorer: 'https://goerli.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'goerli',
    url: 'https://rpc.ankr.com/eth_goerli',
    chainId: 5,
    symbol: 'ETH',
    block_explorer: 'https://goerli.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'goerli',
    url: 'https://goerli.blockpi.network/v1/rpc/public',
    chainId: 5,
    symbol: 'ETH',
    block_explorer: 'https://goerli.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'goerli',
    url: 'https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161',
    chainId: 5,
    symbol: 'ETH',
    block_explorer: 'https://goerli.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'goerli',
    url: 'https://eth-goerli.g.alchemy.com/v2/demo',
    chainId: 5,
    symbol: 'ETH',
    block_explorer: 'https://goerli.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'goerli',
    url: 'https://eth-goerli.api.onfinality.io/public',
    chainId: 5,
    symbol: 'ETH',
    block_explorer: 'https://goerli.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'goerli',
    url: 'https://rpc.goerli.mudit.blog',
    chainId: 5,
    symbol: 'ETH',
    block_explorer: 'https://goerli.etherscan.io/',
    type: 'Testnet',
  },
  {
    network: 'goerli',
    url: 'https://endpoints.omniatech.io/v1/eth/goerli/public',
    chainId: 5,
    symbol: 'ETH',
    block_explorer: 'https://goerli.etherscan.io/',
    type: 'Testnet',
  },
];
const migration = async (db: DbState) => {
  console.log('Running migration 1');
  const versions: { [key: string]: number } = {};
  let id = await db.getLargestNetworkid();
  db.addNetwork(
    rpcs.map(({ network, url, chainId }) => {
      if (versions[network] === undefined) {
        versions[network] = 0;
      } else {
        versions[network] += 1;
      }
      return {
        id: ++id,
        alias:
          versions[network] === 0 ? network : `${network}${versions[network]}`,
        rpc: url,
        chainId:
          chainId === null || chainId === undefined
            ? undefined
            : typeof chainId === 'string'
            ? parseInt(chainId, 16)
            : chainId,
        gas: BigInt(0),
      } as Network;
    }),
  );
  db.setMigration(1);
  await db.write();
  return db;
};

export default migration;
